"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.apiPaths = void 0;
var boomtown_config_1 = require("./boomtown-config");
exports.apiPaths = {
    getCustomerApi: generatePath("customers/get"),
    getCustomerByIdApi: function (id) { return generatePath("customers/get/" + id); },
    createUpdateCustomerApi: generatePath("customers/put"),
    deleteCustomerApi: function (id) { return generatePath("customers/delete/" + id); },
    customerMetaStatus: generatePath("customers/meta/statuses"),
    customerMetaIndustries: generatePath("customers/meta/industries"),
    getCustomerLocationByIdApi: function (id) { return generatePath("customers/location/get/" + id); },
    createUpdateCustomerLocationApi: generatePath("customers/location/put"),
    deleteCustomerLocationApi: function (id) { return generatePath("/customers/location/delete/" + id); },
    getCustomerLocationByExternalIdApi: generatePath("customers/location/lookupByExternalId"),
    getLocationContactByCustomerId: function (customerId) { return generatePath("/customers/location/users/" + customerId); },
    getCustomerLocationMetaStatus: generatePath("customers/location/meta_statuses"),
    customerContactCheck: function (email) { return generatePath("customers/user_check/" + email); },
    customerContactByCustomerId: function (customerId) { return generatePath("customers/user/get/" + customerId); },
    customerContactByExternalId: generatePath("customers/user/lookupByExternalId"),
    createUpdateCustomerContact: generatePath("customers/user/put"),
    customerContactSSO: function (contactId) { return generatePath("customers/user/sso/" + contactId); },
    deleteCustomerContact: function (customerId) { return generatePath("customers/user/delete/" + customerId); },
    getCaseMetaStatusApi: generatePath('issues/meta/statuses'),
    getCaseMetaJobsApi: generatePath('issues/meta/jobs'),
    getCaseMetaCategoriesApi: generatePath('issues/meta/categories'),
    getCaseMetaCategoriesNewApi: generatePath('issues/meta/categories_new'),
    getCaseMetaTagsApi: generatePath('issues/meta/tags'),
    getCaseMetaTypesApi: generatePath('issues/meta/types'),
    getCaseMetaFileTagsApi: generatePath('issues/meta/file_tags'),
    getCaseMetaResolutionsApi: generatePath('issues/meta/resolutions'),
    getCasesApi: generatePath('issues/get'),
    getCasesByIdApi: function (id) { return generatePath("issues/get/" + id); },
    createUpdateCasesApi: generatePath("issues/put"),
    getCaseFileByIdApi: function (issueId) { return generatePath("/issues/files/" + issueId); },
    caseFileUploadApi: function (issueId) { return generatePath("/issues/file/upload/" + issueId); },
    deleteCaseFileByIdApi: function (issueId) { return generatePath("/issues/file/delete/" + issueId); },
    createUpdateCaseLogApi: function (issueId) { return generatePath("/issues/log/put/" + issueId); },
    customerLookup: generatePath('customers/lookup'),
    getLookupByIssueId: generatePath('customers/lookupByIssueId'),
    getLookupById: generatePath('customers/lookupById'),
    getLookupByEmail: generatePath('customers/lookupByEmail'),
    getLookupByExternalId: generatePath('customers/lookupByExternalId'),
    customerMetaCustomForms: generatePath('customers/meta/customForms'),
    customerSmsInviteApi: generatePath('customers/sms_invite'),
    customerPasswordResetApi: generatePath('customers/password_reset'),
    getCaseLogByIdApi: function (issueId) { return generatePath("/issues/log/history/" + issueId); },
    deleteCaseLogApi: function (issueId) { return generatePath("/issues/log/delete/" + issueId); },
    caseScheduleByIdApi: function (issueId) { return generatePath("/issues/schedule/" + issueId); },
    caseCancelScheduleByIdApi: function (issueId) { return generatePath("/issues/cancel_schedule/" + issueId); },
    caseResolveByIdApi: function (issueId) { return generatePath("/issues/resolve/" + issueId); },
    caseEscalateByIdApi: function (issueId) { return generatePath("/issues/escalate/" + issueId); },
    caseDeEscalateByIdApi: function (issueId) { return generatePath("/issues/deescalate/" + issueId); },
    caseCancelByIdApi: function (issueId) { return generatePath("/issues/cancel/" + issueId); },
    caseStatusByIdApi: function (issueId) { return generatePath("/issues/status/history/" + issueId); },
    caseChatHistoryByIdApi: function (issueId) { return generatePath("/issues/chat/history/" + issueId); },
};
function generatePath(path) {
    return boomtown_config_1.BoomtownConfig.baseApiUrl + path;
}
//# sourceMappingURL=api-paths.js.map