steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'sonarqube:community']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-i', 'sonarqube:community', 'bash']

- name: gcr.io/cloud-builders/npm
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cd sdk
    npm run sonar
